# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f4bed3750da03627c85466bf90a20b3dd629fbb0a331e56353d487c4b352fc3553f459c89fab3e788a44e87b6534f3f15d527818bb7647644de51960385c881c

test:
  secret_key_base: 520f3d481d2f202884768432272006a8457d9022698cf79fa068fab8dc4406eec247d3726671c0cf6a9a2af9691d104742dbb0f88acfea4182b171f6c87c9431

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
